//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRemerasSport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class remera
    {
        public int remera_id { get; set; }
        public string nombre_remera { get; set; }
        public string talla { get; set; }
        public Nullable<int> precio { get; set; }
        public string image { get; set; }
    }
}
